# Generated by Django 3.1.4 on 2020-12-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
