# Generated by Django 3.1.4 on 2020-12-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
    ]
