# Generated by Django 3.1.4 on 2021-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_remove_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='fame',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
