# Generated by Django 3.1.4 on 2021-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_songs_fame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='fame',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
